import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import MainNavbar from "./components/MainNavbar";
import 'bootstrap/dist/css/bootstrap.min.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavbar/>
        <Footer/>
        {children}</body>
    </html>
  );
}
